"""
    The evaluator for LegoNE code generated by the LLMs.
"""

from typing import Callable
from auto_design.prompts import (
    NUM_PLAYER_DECLARE,
    BUILDING_BLOCKS,
    INHERENT_CONSTRAINTS,
)
import subprocess
import os
import re


# The fixed code the evaluator prepends before the LLM's `algo` snippet.
# Compiler line numbers are relative to the full file, so we subtract the
# number of boilerplate lines to map them back onto the LLM's own code.
_BOILERPLATE = NUM_PLAYER_DECLARE + BUILDING_BLOCKS + INHERENT_CONSTRAINTS
_BOILERPLATE_LINES = _BOILERPLATE.count("\n")


def get_approximation(wolfram_output: str):
    # very adhoc, but very useful here
    # Find the last non-empty line in the output
    lines = wolfram_output.strip().split("\n")
    last_line = next(line for line in reversed(lines) if line.strip())
    return float(last_line[0:9]) + 1e-6


def parse_compiler_error(stderr: str) -> str:
    """Extract a precise, LLM-actionable message from the compiler's stderr.

    The compiler emits structured prefixes:
      - "Syntax error: ..."           (lexer/parser, user-fixable)
      - "Semantic error: ..."         (type/symbol checks, user-fixable)
      - "Internal compiler error: ..." (tool limitation, not the user's fault)
    A legacy fallback handles the uncaught-exception "what():" format in case
    an older compiler binary is used.
    """
    stderr = stderr.strip()
    if not stderr:
        return "Unknown system-level error (compiler produced no message)"

    for prefix in ("Semantic error:", "Syntax error:"):
        idx = stderr.find(prefix)
        if idx != -1:
            return stderr[idx + len(prefix):].strip()

    prefix = "Internal compiler error:"
    idx = stderr.find(prefix)
    if idx != -1:
        msg = stderr[idx + len(prefix):].strip()
        return (
            "Internal compiler error (likely a tool limitation, "
            f"try a different algorithm): {msg}"
        )

    # Legacy fallback: uncaught C++ exception printed by std::terminate.
    marker = "what():"
    idx = stderr.find(marker)
    if idx != -1:
        return stderr[idx + len(marker):].strip()

    return f"Unknown compiler error: {stderr}"


def add_code_context(err_str: str, algo_code: str) -> str:
    """Attach the relevant slice of the LLM's algorithm to a compiler error.

    Compiler diagnostics carry line numbers relative to the full generated
    file (fixed boilerplate + the LLM's `algo` code). The LLM only ever sees
    its own snippet, so a bare "line 88" is meaningless to it. This:
      1. maps the file line back to a line of the LLM's algorithm,
      2. quotes the offending line, and
      3. appends the full numbered algorithm for context,
    while hiding the internal temp filename and absolute line numbers.
    """
    algo_lines = algo_code.split("\n")
    numbered = "\n".join(f"{i + 1:>3} | {line}" for i, line in enumerate(algo_lines))

    # Extract a file-relative line number: semantic ("line N:") or syntax
    # ("<tmp>.legone:N.col").
    file_line = None
    m = re.search(r"^line (\d+):", err_str)
    if m:
        file_line = int(m.group(1))
    else:
        m = re.search(r"\.legone:(\d+)\.\d", err_str)
        if m:
            file_line = int(m.group(1))

    if file_line is None:
        # No location to map; still give the LLM its own code for context.
        return f"{err_str}\n\nYour algorithm code (with line numbers):\n{numbered}"

    algo_line = file_line - _BOILERPLATE_LINES
    in_algo = 1 <= algo_line <= len(algo_lines)

    # Hide the internal temp filename and rewrite to algo-relative numbering.
    err_str = re.sub(
        r"[^\s:]*__eval_temp\.legone:\d+\.([\d.\-]+):?", r"column \1:", err_str
    )
    err_str = re.sub(
        r"^line \d+:", f"line {algo_line}:" if in_algo else "", err_str
    ).strip()

    if in_algo:
        pointer = (
            f"\n\nThe error is at line {algo_line} of your algorithm:\n"
            f"    {algo_lines[algo_line - 1].strip()}"
        )
    else:
        pointer = (
            "\n\n(The error comes from a provided building block, "
            "not from your algorithm code.)"
        )

    return f"{err_str}{pointer}\n\nYour algorithm code (with line numbers):\n{numbered}"


class Evaluator(object):
    """Evaluates LegoNE code by compiling and calculating approximation bound.
    
    This class handles the pipeline of:
    1. Generating complete LegoNE code from algorithm snippets
    2. Compiling LegoNE to Mathematica code
    3. Computing approximation bound using Mathematica
    
    Args:
        compiler_path (str): Path to the LegoNE compiler executable
        optimizer_name (str, optional): Name of Mathematica executable. Defaults to "wolframscript"
        logger (Callable[[str], None], optional): Function for logging output. 
            Defaults to no-op function.
    """

    def __init__(
        self,
        compiler_path: str,
        optimizer_name: str = "wolframscript",
        logger: Callable[[str], None] = lambda msg: None,
    ):
        self.optimizer_name = optimizer_name
        self._last_algo_code = ""
        self.temp_legone_name = "__eval_temp.legone"
        self.temp_wolfram_name = "__eval_temp.m"
        self.compiler_args = [
            compiler_path,
            self.temp_legone_name,
            "-o",
            self.temp_wolfram_name,
        ]
        self.optimizer_args = [
            optimizer_name,
            "-file",
            self.temp_wolfram_name,
            "-l",
            "-print",
        ]
        self.logger = logger
        self.logger(
            "\033[1;95mInitializing Evaluator with the following configuration:\033[0m\n"
        )
        self.logger(f"optimizer_name: {self.optimizer_name}")
        self.logger(f"compiler_path: {compiler_path}")
        self.logger(f"temp_legone_name: {self.temp_legone_name}")
        self.logger(f"temp_wolfram_name: {self.temp_wolfram_name}")
        self.logger("compiler_args: " + str(self.compiler_args))
        self.logger("optimizer_args: " + str(self.optimizer_args) + "\n")

    def gen_legone_code(self, algo_code: str):
        self.logger("\033[1;95mEvaluator is generating LegoNE code...\033[0m")
        self._last_algo_code = algo_code
                # check if both player has at most three strategies
        p1_count = algo_code.replace(" ", "").count(":p1")
        p2_count = algo_code.replace(" ", "").count(":p2")
        if p1_count > 3 or p2_count > 3:
                self.logger("\033[1;91mFailed. Each player can have at most 3 strategies. Cannot use!\033[0m")
                return "Each player can have at most 3 strategies. Cannot use!"
        legone_code = (
            NUM_PLAYER_DECLARE + BUILDING_BLOCKS + INHERENT_CONSTRAINTS + algo_code
        )
        with open(self.temp_legone_name, "w") as f:
            f.write(legone_code)
        self.logger(
            f"""\033[1;92mSucceeded. Evaluator has generated the following LegoNE code:\033[0m
\033[1;92m{' LegoNE code begins '.center(100, '=')}\033[0m
"""
        )
        self.logger(legone_code)
        self.logger(f"\033[1;92m{' LegoNE code ends '.center(100, '=')}\033[0m\n")

        return None


    def gen_wolfram_code(self):
        self.logger("\033[1;95mEvaluator is generating mathematica code...\033[0m")
        try:
            # Run the compiler to generate Wolfram code
            compiler_process = subprocess.run(
                self.compiler_args,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            # Check for errors in the compiler output
            if compiler_process.stderr or compiler_process.returncode != 0:
                err_str = parse_compiler_error(compiler_process.stderr)
                err_str = add_code_context(err_str, self._last_algo_code)
                self.logger(
                    f"\033[1;91mFailed. Evaluator encounters a compile error: {err_str}\033[0m"
                )
                return err_str

            # If no errors, record the output and return None
            with open(self.temp_wolfram_name, "r") as f:
                self.logger(
                    f"""\033[1;92mSucceeded. Evaluator has generated the following mathematica code:\033[0m
\033[1;92m{' mathematica code begins '.center(100, '=')}\033[0m
"""
                )
                self.logger(f.read())
                self.logger(f"\033[1;92m{' mathematica code ends '.center(100, '=')}\033[0m\n")

            return None

        except Exception as e:
            # Catch any unexpected exceptions and return as unknown error
            self.logger(
                f"\033[1;91mFailed. Evaluator encounters unknown error: {e}\033[0m"
            )
            return f"Unknown error: {str(e)}"

    def cal_approx(self):
        self.logger(
            "\033[1;95mEvaluator is computing the approximation of the generated algorithm...\033[0m"
        )
        try:
            # Run the optimizer to calculate approximation bound
            optimizer_process = subprocess.run(
                self.optimizer_args,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            # Check for errors in the optimizer output
            if optimizer_process.stderr or optimizer_process.returncode != 0:
                stderr = optimizer_process.stderr
                if not stderr:
                    self.logger(
                        "\033[1;91mFailed. Evaluator encounters a unknown system-level error\033[0m"
                    )
                    return "Unknown system-level error"
                self.logger(
                    f"\033[1;91mFailed. Evaluator encounters a runtime error: {stderr}\033[0m"
                )
                return f"Unknown error: {stderr}"

            # If no errors, record the output and return None
            wolfram_output = optimizer_process.stdout
            self.logger(
                f"""\033[1;92mSucceeded. Here is the output of mathematica:\033[0m
\033[1;92m{' mathematica output begins '.center(100, '=')}\033[0m
"""
            )
            self.logger(wolfram_output)
            self.logger(f"\033[1;92m{' mathematica output ends '.center(100, '=')}\033[0m\n")
            self.approximation = get_approximation(wolfram_output)
            self.logger(
                f"\033[1;92mEvaluator got approximation: {self.approximation}\033[0m"
            )
            if self.approximation <= 1e-4:
                self.logger("\033[1;93mWarning: Mathematica may fail to converge...Try again\033[0m")
                # try again
                self.approximation = get_approximation(wolfram_output)
                self.logger(
                f"\033[1;92mEvaluator got approximation: {self.approximation}\033[0m"
                )
                if self.approximation <= 1e-4:
                    self.logger("\033[1;93mWarning: Mathematica may fail to converge for the second trial\033[0m")
                    return "Got approximation 0.0. It indicates that the computation may fail to converge. Try simpler algorithm."
            
            return None

        except Exception as e:
            # Catch any unexpected exceptions and return as unknown error
            self.logger(
                f"\033[1;91mFailed. Evaluator encounters unknown error: {e}\033[0m"
            )
            return f"Unknown error: {str(e)}"

    def clear_temp_files(self):
        try:
            os.remove(self.temp_legone_name)
        except:
            pass
        try:
            os.remove(self.temp_wolfram_name)
        except:
            pass

    def eval(self, algo_code: str):
        """Evaluate a LegoNE algorithm code snippet.
        
        This is the main public interface for evaluation. It:
        1. Generates complete LegoNE code
        2. Compiles to Mathematica
        3. Calculates approximation bound
        4. Cleans up temporary files
        
        Args:
            algo_code (str): The LegoNE algorithm code snippet to evaluate

        Returns:
            tuple[Literal[False], str] | tuple[Literal[True], float]: A tuple where:
                - If evaluation fails: (False, error_message)
                - If evaluation succeeds: (True, approximation_bound)
        """
        # First generate legone code
        gen_code_error = self.gen_legone_code(algo_code)
        if gen_code_error:
            return False, gen_code_error

        # Then compile to wolfram code
        compile_error = self.gen_wolfram_code()
        if compile_error:
            self.clear_temp_files()
            return False, compile_error

        # Finally calculate approximation bound
        calc_error = self.cal_approx()

        self.clear_temp_files()
        if calc_error:
            return False, calc_error

        return True, self.approximation


# class Evaluator
